### ISSUE TITLE
代码错误

### ISSUE THREAD

**Issue by nulloption** [JoaquinChou/SigSiamPlus#1]
The code is not running because there are many .npy files mentioned in ./SigSiamPlus-master/data_txt/cwru/cwru_DE_1730_RPM_copy_014_021_train.txt that do not exist in ./SigSiamPlus-master/data/cwru/DE/1730_RPM_copy/014_021 directory. It keeps throwing errors. It seems there might be an issue with the file paths or the data directory setup. Could you please check and ensure that the necessary .npy files are present in the specified directories?
![a6a7734c6101e8ef0f32e25b2fb259b](https://github.com/user-attachments/assets/4d413304-24bc-4299-a76f-334ac80aadbd)

**Comment by JoaquinChou** [comment]
Thank you for your question. And please check that whether your file path is existed, we set the path as this "../data/cwru/DE/1730_RPM_copy/007_021/" with "_".

**Comment by nulloption** [comment]
这里是带有“_”的，只是截图没有截取。在您的代码中data_txt/cwru/cwru_DE_1730_RPM_copy_014_021_train.txt中一些.npy文件是data/cwru/DE/1730_RPM_copy/014_021/B中没有的。所以代码根本跑不起来

**Comment by nulloption** [comment]
[图片]
![a79ef29bdd97b237076848850125e06](https://github.com/user-attachments/assets/b46a9b8d-7438-4ca9-b234-405db0b57c83)

就比如这里的../data/cwru/DE/1730_RPM_copy/007_021//B/502.npy文件，在data/cwru/DE/1730_RPM_copy/014_021/B中没有的

**Comment by nulloption** [comment]
![f194a78f94bea38ad837f77d23d29a1](https://github.com/user-attachments/assets/910287bb-6f60-47de-9965-762c05cb455c)

**Comment by JoaquinChou** [comment]
请认真检查下文件信息哈
![20240715-155551](https://github.com/user-attachments/assets/8dcdd884-6d02-48e0-8d74-8462f8507284)

**Comment by nulloption** [comment]
![20240808123821](https://github.com/user-attachments/assets/4b3ff5e9-4023-4563-ac9f-2fc3346562a2)
作者你好，这里我运行了python main_sigsiam.py --batch_size 1024 --learning_rate 0.1  --temp 0.7 --cosine --dataset CWRU_signal_cross_domain --epoch 1000 --model DRSN-SA > temp.txt，最后还是报错。说明你的文件夹里面还是少了文件
